name: flutter_package_name_icon
description: A package which you can update app package (bundleId), app name and app icon.
version: 0.0.1
author: ibrahimkarahan <ibrahimkarahan2@yandex.com>
homepage: https://github.com/devibrahimkarahan/flutter_package_name_icon

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter_launcher_icons: ^0.7.4
  yaml: ^2.2.0
  args: ^1.5.2
  flutter_native_splash:
    git: git://github.com/devibrahimkarahan/flutter_native_splash.git

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
# assets:
#  - images/a_dot_burr.jpeg
#  - images/a_dot_ham.jpeg